# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hW4LzUFKsXUPjoGWTeseVCcNBM2pDPmH
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

iris = load_iris()
X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def create_model(learning_rate):
    model=Sequential()
    model.add(Dense(10,activation='relu',input_shape=(4,)))
    model.add(Dense(8,activation='relu'))
    model.add(Dense(5,activation='relu'))
    model.add(Dense(3,activation='softmax'))

    optimizer = SGD(learning_rate=learning_rate)
    model.compile(optimizer=optimizer,loss='sparse_categorical_crossentropy',metrics=['accuracy'])
    return model

learning_rates=[0.01,0.1,1.0]
epochs_list = [20,50,100]

results = {}

for lr in learning_rates:
    for epochs in epochs_list:
        print(f"\nTraining with Learning Rate={lr}, Epochs={epochs}")

        model = create_model(lr)

        history = model.fit(
            X_train,
            y_train,
            epochs=epochs,
            validation_split=0.2,
            verbose=0
        )

        test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)

        results[(lr, epochs)] = {
            'accuracy': test_acc,
            'history': history.history
        }

        print("Test Accuracy:", round(test_acc, 4))

history = results[(0.01, 50)]['history']

plt.plot(history['accuracy'], label='Training Accuracy')
plt.plot(history['val_accuracy'], label='Validation Accuracy')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.show()

print("\nSummary")
print("-------------------------------------------")
print("Learning Rate\tEpochs\tTest Accuracy")
print("-------------------------------------------")

for key, value in results.items():
    print(f"{key[0]}\t\t{key[1]}\t{value['accuracy']:.4f}")

